-- MySQL Script generated by MySQL Workbench
-- Sat Jul 17 18:39:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Exercici5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Exercici5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exercici5` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Exercici6
-- -----------------------------------------------------
USE `Exercici5` ;

-- -----------------------------------------------------
-- Table `Exercici5`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(45) NOT NULL,
  `emailUser` VARCHAR(45) NOT NULL,
  `passwordUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`User_Relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`User_Relationship` (
  `idUser_Relationship` INT NOT NULL AUTO_INCREMENT,
  `typeRelation` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  `User_idUser1` INT NOT NULL,
  PRIMARY KEY (`idUser_Relationship`, `User_idUser`, `User_idUser1`),
  UNIQUE INDEX `idUser_Relationship_UNIQUE` (`idUser_Relationship` ASC) VISIBLE,
  UNIQUE INDEX `typeRelation_UNIQUE` (`typeRelation` ASC) VISIBLE,
  INDEX `fk_User_Relationship_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_User_Relationship_User2_idx` (`User_idUser1` ASC) VISIBLE,
  CONSTRAINT `fk_User_Relationship_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Exercici5`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Relationship_User2`
    FOREIGN KEY (`User_idUser1`)
    REFERENCES `Exercici5`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`Photo_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`Photo_User` (
  `idPhoto_User` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  `url_photo` VARCHAR(100) NOT NULL,
  `User_Relationship_idUser_Relationship` INT NOT NULL,
  PRIMARY KEY (`idPhoto_User`),
  UNIQUE INDEX `idPhoto_User_UNIQUE` (`idPhoto_User` ASC) VISIBLE,
  INDEX `fk_Photo_User_User_Relationship_idx` (`User_Relationship_idUser_Relationship` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_User_User_Relationship`
    FOREIGN KEY (`User_Relationship_idUser_Relationship`)
    REFERENCES `Exercici5`.`User_Relationship` (`idUser_Relationship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`Provider` (
  `nif_Provider` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `fax` INT NULL,
  `street` VARCHAR(45) NULL,
  `num` INT NULL,
  `floor` INT NULL,
  `door` VARCHAR(4) NULL,
  `city` VARCHAR(45) NULL,
  `code` INT NULL,
  PRIMARY KEY (`nif_Provider`),
  UNIQUE INDEX `idProvider_UNIQUE` (`nif_Provider` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`Brand` (
  `nameBrand` INT NOT NULL,
  `nif_Provider` INT NULL,
  `Provider_nif_Provider` INT NOT NULL,
  PRIMARY KEY (`nameBrand`),
  INDEX `fk_Brand_Provider1_idx` (`Provider_nif_Provider` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Provider1`
    FOREIGN KEY (`Provider_nif_Provider`)
    REFERENCES `Exercici5`.`Provider` (`nif_Provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(200) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dateRegister` DATETIME NOT NULL,
  `testimonial` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `idCustomer_UNIQUE` (`idCustomer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`Seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`Seller` (
  `idSeller` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSeller`),
  UNIQUE INDEX `idSeller_UNIQUE` (`idSeller` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici5`.`Glass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici5`.`Glass` (
  `idGlass` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `right_lens` INT NOT NULL,
  `left_lens` INT NOT NULL,
  `frame` VARCHAR(45) NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `color_lens_R` VARCHAR(45) NOT NULL,
  `color_lens_L` VARCHAR(45) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `Provider_nif_Provider` INT NOT NULL,
  `Brand_nameBrand` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Seller_idSeller` INT NOT NULL,
  PRIMARY KEY (`idGlass`),
  UNIQUE INDEX `idGlass_UNIQUE` (`idGlass` ASC) VISIBLE,
  INDEX `fk_Glass_Provider1_idx` (`Provider_nif_Provider` ASC) VISIBLE,
  INDEX `fk_Glass_Brand1_idx` (`Brand_nameBrand` ASC) VISIBLE,
  INDEX `fk_Glass_Customer1_idx` (`Customer_idCustomer` ASC) VISIBLE,
  INDEX `fk_Glass_Seller1_idx` (`Seller_idSeller` ASC) VISIBLE,
  CONSTRAINT `fk_Glass_Provider1`
    FOREIGN KEY (`Provider_nif_Provider`)
    REFERENCES `Exercici5`.`Provider` (`nif_Provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glass_Brand1`
    FOREIGN KEY (`Brand_nameBrand`)
    REFERENCES `Exercici5`.`Brand` (`nameBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glass_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `Exercici5`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glass_Seller1`
    FOREIGN KEY (`Seller_idSeller`)
    REFERENCES `Exercici5`.`Seller` (`idSeller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
